version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      # Railway sẽ yêu cầu cung cấp biến này qua UI hoặc CLI
      MYSQL_DATABASE: sales_app
      MYSQL_USER: sales_user
      MYSQL_PASSWORD: sales_password
    ports:
      - "3306:3306"  # Railway có thể bỏ qua port này, nhưng giữ để local vẫn chạy
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sales_app
      SPRING_DATASOURCE_USERNAME: sales_user
      SPRING_DATASOURCE_PASSWORD: sales_password
      JWT_SECRET: ${JWT_SECRET}
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  mysql_data:
